<?php
?>


<?php
function removeSpecificTag($html, $tagName) {
    $pattern = "/<{$tagName}([^>]*)>(.*?)<\/{$tagName}>/is";
    $newHtml = preg_replace_callback($pattern, function($matches) {
        return $matches[2]; // Trả về nội dung bên trong thẻ
    }, $html);
    return $newHtml;}
$url= "https://vnexpress.net/rss/kinh-doanh.rss";

$fileContents= file_get_contents($url);
$fileContents=removeSpecificTag($fileContents,"a" );
$fileContents = str_replace(array("<![CDATA["), '', $fileContents);
$fileContents = str_replace(array("]]>"), ' </thumbnail>
    ', $fileContents);
$fileContents = str_replace(array('" ></br>'), ' ]]></img>
    <thumbnail>', $fileContents);
$fileContents = str_replace(array('<img src="'), '
    <img><![CDATA[ ', $fileContents);

 $fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
$fileContents = trim(str_replace('"', "'", $fileContents));
$simpleXml = new SimpleXMLElement($fileContents);
?>
<div class="container">
  <div class="row">
      <ul class="cards">
          <?php foreach ($simpleXml->channel->item  as $item) : ?>
          <li>
              <a href="<?= $item->link->__toString() ?>" class="card">
                  <img src="<?= $item->description->img->__toString() ?>" class="card__image" alt="" />
                  <div class="card__overlay">
                      <div class="card__header">
                          <svg class="card__arc" xmlns="http://www.w3.org/2000/svg"><path /></svg>
                          <div class="card__header-text">
                              <h3 class="card__title"><?= $item->title->__toString() ?></h3>
                              <span class="card__status"><?= $item->pubDate->__toString() ?></span>
                          </div>
                      </div>
                      <p class="card__description"><?= $item->description->thumbnail->__toString() ?></p>
                  </div>
              </a>
          </li>
          <?php endforeach; ?>
  </div>
</div>

<style>
    * {
        box-sizing: border-box;
    }
    .cards{
        width:100%
    }

    body {
        font-family: 'Noto Sans JP', sans-serif;
        background-color: #FFFFFFFF;
    }

    .cards {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(370px, 1fr));
        gap: 2rem;
        padding: 0;
        list-style-type: none;
    }

    .card {
        position: relative;
        display: block;
        height: 100%;
        border-radius: 1px;
        overflow: hidden;
        text-decoration: none;
    }

    .card__image {
        width: 100%;
        height: auto;
    }

    .card__overlay {
        position: absolute;
        bottom: 0;
        left: 0;
        right: 0;
        z-index: 1;
        border-radius: 1px;
        background-color:#f8f8f8;
        transform: translateY(100%);
        transition: .2s ease-in-out;
    }

    .card:hover .card__overlay {
        transform: translateY(0);
    }

    .card__header {
        min-height: 75px;
        position: relative;
        display: flex;
        align-items: center;
        gap: 2em;
        padding: 10px;
        border-radius: 1px 0 0 0;
        background-color: #f8f8f8;
        transform: translateY(-100%);
        transition: .2s ease-in-out;
    }

    .card__arc {
        width: 80px;
        height: 80px;
        position: absolute;
        bottom: 100%;
        right: 0;
        z-index: 1;
    }

    .card__arc path {
        fill: #f8f8f8;
        d: path("M 40 80 c 22 0 40 -22 40 -40 v 40 Z");
    }

    .card:hover .card__header {
        transform: translateY(0);
    }

    .card__thumb {
        flex-shrink: 0;
        width: 50px;
        height: 50px;
        border-radius: 50%;
    }

    .card__title {
        font-size: 1em;
        margin: 0 0 .3em;
        color: rgba(0, 0, 0, 0.90);
    }

    .card__tagline {
        display: block;
        margin: 1em 0;
        font-family: "MockFlowFont";
        font-size: .8em;
        color: rgba(0, 0, 0, 0.90);
    }

    .card__status {
        font-size: .8em;
        color: rgba(0, 0, 0, 0.90);
    }

    .card__description {
        padding: 0 2em 2em;
        margin: 0;
        color: rgba(0, 0, 0, 0.90);
        font-family: "MockFlowFont";
        display: -webkit-box;
        -webkit-box-orient: vertical;
        -webkit-line-clamp: 3;
        overflow: hidden;
    }
</style>
