<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
  integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<?php

/**
 * @var \Modules\News\Block\NewsBlock $block
 */
?>

<div id="content"></div>
<?php
function removeSpecificTag($html, $tagName) {
    $pattern = "/<{$tagName}([^>]*)>(.*?)<\/{$tagName}>/is";
    $newHtml = preg_replace_callback($pattern, function($matches) {
        return $matches[2]; // Trả về nội dung bên trong thẻ
    }, $html);
    return $newHtml;}
$url= "https://vnexpress.net/rss/kinh-doanh.rss";

$fileContents= file_get_contents($url);
$fileContents=removeSpecificTag($fileContents,"a" );
$fileContents = str_replace(array("<![CDATA["), '', $fileContents);
$fileContents = str_replace(array("]]>"), ' </thumbnail>
    ', $fileContents);
$fileContents = str_replace(array('" ></br>'), ' ]]></img>
    <thumbnail>', $fileContents);
$fileContents = str_replace(array('<img src="'), '
    <img><![CDATA[ ', $fileContents);

 $fileContents = str_replace(array("\n", "\r", "\t"), '', $fileContents);
$fileContents = trim(str_replace('"', "'", $fileContents));
$simpleXml = new SimpleXMLElement($fileContents);

// Lấy giá trị CDATA của phần tử "data"
//$simpleXml = simplexml_load_string($fileContents);
//$json = json_encode($simpleXml);
//$data = json_decode($json, true);
?>
<div class="container">
  <div class="row">

    <?php foreach ($simpleXml->channel->item  as $item) : ?>
    <div class="col-sm-6">
      <div class="card flex-md-row mb-4 box-shadow h-md-250">
        <div class="row">
          <div class="col-sm-7">
            <div class="card-body d-flex flex-column align-items-start">
              <strong class="d-inline-block mb-2 text-primary">Tin tức</strong>
              <h4 class="mb-0">
                <a class="text-dark font-weight-bold" href="<?= $item->link->__toString() ?>"><?= $item->title->__toString() ?></a>
              </h4>
              <p class="card-text mb-auto"><?= $item->description->thumbnail->__toString() ?></p>
<!--                <p class="card-text mb-auto">--><?php //= $item->img->to_string() ?><!--</p>-->
            </div>
          </div>
          <div class="col-sm-5">
            <img class="card-img-right flex-auto d-none d-md-block w-100" data-src="<?= $item->description->thumbnail->__toString() ?>"
                 style="width: 250px; height: 150px;" src="<?= $item->description->img->__toString() ?>" data-holder-rendered="true">
          </div>
        </div>
      </div>
    </div>
    <?php endforeach; ?>
  </div>
</div>
