<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<div class="container">
    <div class="row">
        <h4 style="margin-top: 20px">Hướng dẫn sử dụng </h4>
        <ul class="list-unstyled">
            <ul>
                <li><h5>Mục đích:</h5>
                    <ul>
                        <li>Nhằm lấy thông tin sản phẩm đơn giản hơn cho các nhà phát triển.</li>
                        <li>Phục vụ cho quảng cáo sản phẩm ở các trang Web khác</li>
                    </ul>
                </li>
            </ul>

            <ul>
                <li><h5>Chức năng:</h5>
                    <ul>
                        <li>Lấy thông tin sản phẩm bằng ID của sản phẩm.</li>
                        <li>Lấy thông tin sản phẩm bằng SKU của sản phẩm.</li>
                        <li>Lấy thông tin các sản phẩm có cùng Category ID và Category Name.</li>
                    </ul>
                </li>
            </ul>
            <ul>
                <li><h5>Hướng dẫn sử dụng:</h5>
                    <ul>
                        <li>Lấy thông tin sản phẩm bằng ID của sản phẩm.
                            <ul>http://beosstore.site/rest/V1/products/id/:id
                                (với :id thay bằng id của sản phẩm vd: id = 2047)
                            </ul>
                        </li>
                        <li>Lấy thông tin sản phẩm bằng SKU của sản phẩm.
                            <ul>http://beosstore.site/rest/V1/products/sku/:sku
                                (với :sku thay bằng SKU của sản phẩm vd: sku = SRPG25J1)
                            </ul>
                        </li>
                        <li>Lấy thông tin các sản phẩm có cùng Category ID và Category Name.
                            <ul>http://beosstore.site/rest/V1/products/category/:cid
                                (với :cid thay bằng CategoryId vd: cid = 20)
                            </ul>
                        </li>
                    </ul>
                </li>
            </ul>
        </ul>
    </div>
</div>
<style>
    /* Custom CSS */
    body {
        font-family: Arial, sans-serif;
        background-color: #f8f8f8;
    }

    .container {
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
    }

    h4 {
        margin-top: 0;
        color: #333;
    }

    ul.list-unstyled {
        margin-bottom: 20px;
    }

    ul.list-unstyled li {
        margin-bottom: 10px;
    }

    ul.list-unstyled ul {
        margin-left: 20px;
    }

    ul.list-unstyled ul li {
        margin-bottom: 5px;
    }
</style>
